name: 'QnA Maker Knowledgebase Operations'
description: 'Update, train or publish QnA Maker Knowledgebases'
inputs:
  operation:  
    description: 'Type of operation to run: update, train, publish'
    required: true
    default: 'update'
  credentials:
    description: 'QnA API Key'
    required: true
  endpoint:
    description: 'QnA Maker endpoint'
    required: true
    default: 'https://westus.api.cognitive.microsoft.com/qnamaker/v2.0'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
