name: 'QnA Maker Knowledgebase Operations'
description: 'Update, train or publish QnA Maker Knowledgebases'
inputs:
  operation:  
    description: 'Type of operation to run: testContent, update, train, publish'
    required: true
    default: 'update'
  api-key:
    description: 'QnA Authoring Subscription Key'
    required: true
  endpoint:
    description: 'QnA Maker authoring endpoint'
    required: true
    default: 'https://YOUR-RESOURCE-NAME.cognitiveservices.azure.com'
  kbId:
    description: 'Knowledge base id'
    required: true
  path-to-kb:
    description: 'path to the KB .xls file, for example: "qna/my backup/my kb.xls"'
    required: true
  kb-filename:
    description: 'name of the file, for example: "my kb.xls", for updates it will overwrite the contents under this name'
    required: true
  kb-language:
    description: 'Language for the KB'
    required: true
    default: 'English'
  delete-editorial:
    description: 'Mark to true to also remove the manually edited contents before the update'
    default: false
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The operation result'
runs:
  using: 'node16'
  main: 'dist/index.js'
